version: "3"
services:
    api:
        build:
            dockerfile: Dockerfile
            context: ./server
    client:
        build:
            dockerfile: Dockerfile
            context: ./client
    nginx:
        depends_on:
            - api
            - client
        restart: always
        build:
            dockerfile: Dockerfile
            context: ./nginx
        ports:
            - "80:80"

