apiVersion: v1
kind: Service
metadata:
  name: client-service
  labels:
    app: client
spec:
  type: NodePort
  selector:
    app: client 
  ports:
    - port: 7001
      targetPort: 7001
      nodePort: 30007
