apiVersion: v1
kind: Service
metadata:
  name: server-service
  labels:
    app: server
spec:
  type: NodePort
  selector:
    app: server 
  ports:
    - port: 8001
      targetPort: 8001
      nodePort: 30008
